// clipwatch — 맥 클립보드 변경을 감시해 JSON 한 줄씩 stdout 으로 흘린다.
//
// pbpaste 폴링 대신 NSPasteboard.changeCount 를 본다. 이유는 둘:
//   1) 바뀌지 않았으면 내용을 아예 안 읽는다 (CPU 0 에 가깝다)
//   2) 타입 목록을 볼 수 있다 → 비밀번호 관리자가 붙이는 concealed 플래그를 걸러낸다.
//      pbpaste 로는 이 구분이 불가능하다. 자동 동기화에서 이건 안전장치다.
//
// 빌드: swiftc -O -o clipwatch clipwatch.swift

import AppKit
import Foundation

let concealedTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",      // 1Password·Keychain 등이 붙인다
    "org.nspasteboard.TransientType",      // 클립보드 매니저가 담지 말라는 표시
    "org.nspasteboard.AutoGeneratedType",  // 사람이 복사한 게 아님
]

struct Event: Codable {
    let n: Int
    let concealed: Bool
    let text: String
}

let pb = NSPasteboard.general
var last = pb.changeCount
let encoder = JSONEncoder()
encoder.outputFormatting = []

// 시작 시점의 클립보드는 보내지 않는다 — 기동만으로 폰이 덮이면 놀란다.
while true {
    let now = pb.changeCount
    if now != last {
        last = now
        let types = Set((pb.types ?? []).map { $0.rawValue })
        let concealed = !types.isDisjoint(with: concealedTypes)
        let text = pb.string(forType: .string) ?? ""
        if !text.isEmpty {
            let ev = Event(n: now, concealed: concealed, text: text)
            if let data = try? encoder.encode(ev), let line = String(data: data, encoding: .utf8) {
                print(line)
                fflush(stdout)
            }
        }
    }
    usleep(400_000)   // 0.4초
}
